- app/controllers/artists_controller.rb
- app/controllers/cart_histries_controller.rb
- app/controllers/carts_controller.rb
- app/controllers/discs_controller.rb
- app/controllers/events_controller.rb
- app/controllers/following_artists_controller.rb
- app/controllers/history_controller.rb
- app/controllers/items_controller.rb
- app/controllers/musics_controller.rb
- app/controllers/users_controller.rb
- config/routes.rb
> [create] routing

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/models/artist.rb
- app/models/item.rb
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- config/initializers/kaminari_config.rb
[Updated]Update Gemfile **#Gemfileへのgem追加**
- [Finished]bundle install **#gemのインストール**
- [Updated]assets/javascripts/application.js **#bootstrap/ransackに必要な記述の追加**
- [Updated]assets/stylesheets/application.css **#bootstrapに必要な記述の追加**
- [Modified]models using refile(artist/item) **#refileを使って画像追加するモデルへ"attachment :image"追加**
> [Updated]Gemfile Install & Settings

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- db/migrate/20190115053555_add_name_to_users.rb
- db/schema.rb
- 新規登録機能の実装
- ログイン機能の実装
※ validatesは未入力の確認、文字制限(郵便番号・電話番号の桁数制限)のみ
> [Updated]Sign in & Sign up

- app/views/layouts/application.html.erb
layout/application.html.erbの更新（ヘッダーの追加）
> [Update] application.html.erb

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
views/layouts/application.html.erb
assets/stylesheets/application.scss/
> [crate] application.html.erb application.scss

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
> [update] application controller.html/css　ヘッダーの更新

- app/views/layouts/application.html.erb
更新しました。同じくヘッダー部分です。
リンク先が飛べるようになってます。
確認をお願いします。
> [update] application html/css

- app/assets/stylesheets/application.scss
- app/controllers/carts_controller.rb
- app/views/carts/index.html.erb
- app/views/layouts/application.html.erb
ヘッダー部分をログイン前とログイン後で変わるようになりました。
cartsのindexを少々追記しました。
> [update] applicatin.html.erb&scss,views/carts/index

- app/assets/stylesheets/application.scss
- app/controllers/carts_controller.rb
- app/views/carts/index.html.erb
- app/views/layouts/application.html.erb
マイページへのヘッダーリンクをaタグから<%= link_to ... %>表記に変更
> [Modified]header link

- app/controllers/artists_controller.rb
- app/views/artists/index.html.erb
- app/views/artists/new.html.erb
- app/views/layouts/application.html.erb
- config/initializers/application_controller_renderer.rb
- config/routes.rb
- db/migrate/20190117052110_remove_image_and_add_image_id_to_artists.rb
- db/migrate/20190117052129_remove_image_and_add_image_id_to_items.rb
- db/schema.rb
**※ pull後、必ず"rails db:migrate"を実行してください。**
- Artistのビュー作成・更新(アーティスト新規追加機能を実装しました)
> [Modified&Updated]Artists

- app/views/carts/index.html.erb
> [update] cart.index

- app/assets/stylesheets/carts.scss
- app/controllers/carts_controller.rb
- app/views/carts/confirm.html.erb
- app/views/carts/index.html.erb
> [update]carts/index [create]confirm.html.erb

- app/controllers/following_artists_controller.rb
- app/models/artist.rb
- app/views/artists/show.html.erb
- app/views/layouts/application.html.erb
- app/views/managers/sessions/new.html.erb
- config/routes.rb
* 管理者ログイン時のヘッダー表示のエラー解消
- ヘッダーでエラーが発生したため、コードに一部修正を加えました(コンフリクトの可能性あり)
* アーティストのフォロー機能実装
* 管理者ログイン画面の一部変更
> Some changes (header / manager / following artist)

- app/controllers/labels_controller.rb
- app/models/item.rb
- app/views/items/new.html.erb
- app/views/labels/new.html.erb
- config/routes.rb
* 商品新規追加機能の更新(未完成)
* レーベル新規登録画面の追加
> [Modified]Item new / [Create]Label new view

- app/controllers/histories_controller.rb
- app/views/items/edit.html.erb
- app/views/labels/index.html.erb
変更点
histories_controller
items/edit
> [update] histories_controller

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/artists.scss
- app/controllers/users_controller.rb
- app/views/artists/edit.html.erb
- app/views/artists/index.html.erb
- app/views/artists/show.html.erb
- app/views/events/show.html.erb
- app/views/items/show.html.erb
- app/views/users/index.html.erb
編集ボタン(リンク)を追加しました。
artists/edit
artists/index
artists/show
events/show
items/show
> [create] edit button 

- app/controllers/labels_controller.rb
- app/views/labels/edit.html.erb
- app/views/labels/index.html.erb
labelsの一覧と編集画面を修正しました。
labels_controller
labels/index
labels/edit
> [update] labels_controller labels/index labels/edit

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/users.scss
- app/controllers/artists_controller.rb
- app/controllers/items_controller.rb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
変更点は以下です。
主に新規登録画面、ログイン画面のcssを変更しました。
header 
registration/new.html 
sessions/new.html
artists_controller
> [update] header registration/new.html sessions/new.html

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/artists.scss
- app/views/artists/index.html.erb
- app/views/items/index.html.erb
- app/views/items/new.html.erb
デザイン面を実装しました。
view artists/index items/index：中央寄せに統一
items/new：(税込)の表示を追加
> [update]view CSS artists/index items/index items/new

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/users.scss
- app/views/carts/index.html.erb
- app/views/following_artists/index.html.erb
- app/views/layouts/application.html.erb
- app/views/users/about.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
modified:   app/assets/stylesheets/application.scss
modified:   app/assets/stylesheets/users.scss
modified:   app/views/carts/index.html.erb
modified:   app/views/following_artists/index.html.erb
modified:   app/views/layouts/application.html.erb
modified:   app/views/users/about.html.erb
modified:   app/views/users/edit.html.erb
modified:   app/views/users/show.html.erb
> [modified] users/edit users/show

- app/assets/stylesheets/application.scss
- app/controllers/artists_controller.rb
- app/controllers/cart_histries_controller.rb
- app/controllers/carts_controller.rb
- app/controllers/discs_controller.rb
- app/controllers/events_controller.rb
- app/controllers/genres_controller.rb
- app/controllers/histories_controller.rb
- app/controllers/items_controller.rb
- app/controllers/labels_controller.rb
- app/controllers/musics_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/managers/sessions/new.html.erb
- app/views/users/sessions/new.html.erb
- config/application.rb
- config/locales/devise.ja.yml
● 下記の機能を実装しました。
① devise機能に関わるメッセージ(ログイン・ログアウト・ログイン失敗時など)
② 情報追加・変更・削除時のメッセージ(users/artists/Items/events/cartsの各コントローラに実装)
③ 権限認証系before_actionの準備(各コントローラにコメントで記載しています。実装時コメントを外します。)
> Some Additional Functions

- app/controllers/carts_controller.rb
- app/controllers/events_controller.rb
- app/controllers/items_controller.rb
● インスタンス変数にすべき箇所が、インスタンス変数になっていなかった部分の修正です。
> [Fixed]controllers(items/events/carts)

- app/controllers/carts_controller.rb
- app/controllers/histories_controller.rb
- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/carts/confirm.html.erb
- app/views/histories/index.html.erb
●カート内容確認画面の一部修正
●itemモデルへのバリデーション追加
●購入履歴の更新
> Some changes

- app/controllers/types_controller.rb
- app/views/types/create.html.erb
- app/views/types/new.html.erb
- config/routes.rb
> [Updated]Type

- app/assets/stylesheets/events.scss
- app/assets/stylesheets/items.scss
- app/assets/stylesheets/labels.scss
- app/controllers/events_controller.rb
- app/views/events/edit.html.erb
- app/views/items/new.html.erb
- app/views/labels/index.html.erb
modified:   app/assets/stylesheets/events.scss
modified:   app/assets/stylesheets/items.scss
modified:   app/assets/stylesheets/labels.scss
modified:   app/controllers/events_controller.rb
modified:   app/views/events/edit.html.erb
modified:   app/views/items/new.html.erb
modified:   app/views/labels/index.html.erb
> modified labels items

- app/assets/stylesheets/events.scss
- app/assets/stylesheets/labels.scss
- app/views/events/edit.html.erb
- app/views/events/new.html.erb
- app/views/labels/index.html.erb
- app/views/users/edit.html.erb
modified:   app/assets/stylesheets/events.scss
modified:   app/assets/stylesheets/labels.scss
modified:   app/views/events/edit.html.erb
modified:   app/views/events/new.html.erb
modified:   app/views/labels/index.html.erb
modified:   app/views/users/edit.html.erb
> [modified] a lot of things

- app/assets/stylesheets/events.scss
- app/views/events/new.html.erb
- app/views/labels/index.html.erb
modified:   app/assets/stylesheets/events.scss
modified:   app/views/events/new.html.erb
modified:   app/views/labels/index.html.erb
> [modified] labels events

- app/assets/stylesheets/events.scss
- app/controllers/artists_controller.rb
- app/controllers/carts_controller.rb
- app/controllers/discs_controller.rb
- app/controllers/events_controller.rb
- app/controllers/following_artists_controller.rb
- app/controllers/genres_controller.rb
- app/controllers/histories_controller.rb
- app/controllers/items_controller.rb
- app/controllers/labels_controller.rb
- app/controllers/musics_controller.rb
- app/controllers/types_controller.rb
- app/controllers/users_controller.rb
● 各コントローラーに閲覧権限を設けました。
● event.scssのカッコ閉じを追記しました。
> [Updated]authentications in each controllers

- app/assets/stylesheets/artists.scss
- app/controllers/following_artists_controller.rb
- app/controllers/items_controller.rb
- app/views/artists/edit.html.erb
- app/views/following_artists/_events.html.erb
- app/views/following_artists/index.html.erb
- config/routes.rb
- db/schema.rb
> [update] following-artist controller/index

- app/controllers/carts_controller.rb
- app/controllers/histories_controller.rb
- app/controllers/items_controller.rb
- app/controllers/users_controller.rb
- app/models/artist.rb
- app/models/cart.rb
- app/models/disc.rb
- app/models/event.rb
- app/models/item.rb
- app/models/music.rb
- app/models/user.rb
- app/views/carts/index.html.erb
- app/views/items/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
[購入機能の更新]
- 購入後に商品の在庫数が減少するようになりました
- 在庫数以上の数量を設定しようとすると、エラーが出るようになりました
　(フラッシュメッセージ・ページ遷移)
- その他、エラー箇所の修正
[各モデルへのバリデーションの追加]
- 記入必須の項目にpresenceを付与しました
- その他、暫定的に文字数制限等を付け加えています
> Purchase Function / Model Validations

- app/controllers/carts_controller.rb
- app/controllers/following_artists_controller.rb
- config/routes.rb
> [modified]Following Artists

- app/views/histories/index.html.erb
> [update]histories/index

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/users_controller.rb
- app/views/items/show.html.erb
- app/views/layouts/application.html.erb
- app/views/users/registrations/new.html.erb
- config/locales/devise.ja.yml
- JSが動くようになりました！！！
- その他、細かいバグフィックス
> [Updated]Add JS to Flash message

- app/assets/javascripts/application.js
- app/controllers/artists_controller.rb
- app/models/event.rb
- app/views/artists/show.html.erb
- app/views/artists/show.js.erb
● アーティスト詳細ページのイベント表示に「もっと見る」機能を追加
> [Updated]Artists#show event-more

- app/controllers/items_controller.rb
- app/controllers/users_controller.rb
- app/views/users/edit.html.erb
- config/routes.rb
- 退会機能の実装
・会員削除ボタンをクリック後、自動的にログアウト
・退会後のユーザーのログイン防止
> [Updated]Users#Edit

- app/views/events/edit.html.erb
- app/views/events/new.html.erb
- app/views/items/edit.html.erb
- app/views/layouts/application.html.erb
> [modified]js script-link moved to event views

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/events.scss
- app/assets/stylesheets/history.scss
- app/assets/stylesheets/users.scss
- app/controllers/users_controller.rb
- app/views/artists/index.html.erb
- app/views/events/show.html.erb
- app/views/histories/index.html.erb
- app/views/users/index.html.erb
application.scss
events.scss
history.scss
users.scss
users_controller.rb
artists/index.html.erb
events/show.html.erb
histories/index.html.erb
users/index.html.erb
> [updade]CSS

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/carts.scss
- app/assets/stylesheets/history.scss
- app/assets/stylesheets/items.scss
- app/assets/stylesheets/users.scss
- app/controllers/users_controller.rb
- app/views/carts/index.html.erb
- app/views/histories/index.html.erb
- app/views/histories/show.html.erb
- app/views/items/edit.html.erb
- app/views/items/index.html.erb
- app/views/items/show.html.erb
- app/views/users/edit.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
CSSを編集しました。
userコントローラーは、エラーを修正しようとしましたが、出来ていません。
> [update]CSS

- app/controllers/application_controller.rb
- app/controllers/histories_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/edit.html.erb
- config/routes.rb
● 認証時エラー修正
● 会員編集を確定すると、強制的に退会する不具合を修正
> [Fixed]Auth & Unsubscribe

- app/controllers/users_controller.rb
> [Fixed]Users controller

- app/views/events/edit.html.erb
- app/views/events/show.html.erb
- イベント編集画面でアーティスト名が表示されるよう変更
- イベント詳細画面で「戻る」ボタンがfollowing_artist_pathになっていたのを修正
> [Fixed]events views

- app/controllers/carts_controller.rb
- カートに追加済みの商品について、商品詳細から追加でカートに入れた場合に、別カートが生成される仕様の変更
> [Fixed]carts controller

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/artists.scss
- app/assets/stylesheets/items.scss
- app/views/items/index.html.erb
・商品一覧のBOXの大きさを統一させるためにレイアウトを変更しました。
> [update]CSS items/index

- app/assets/stylesheets/history.scss
- app/controllers/artists_controller.rb
- app/controllers/items_controller.rb
- app/views/histories/index.html.erb
- アーティスト一覧・商品一覧の表示件数を9個に設定
- 購入履歴画面にステータスを表示
> [modified]definited pagenation(Artists#index/Items#index)

- app/assets/stylesheets/following_artists.scss
- app/controllers/following_artists_controller.rb
- app/views/following_artists/index.html.erb
- app/views/following_artists/show.html.erb
following_artistのshow/indexページを編集しました。
indexページでアーティスト一覧を表示し、showページでそのアーティストのCD情報とイベント情報を表示します。
> [modified] following artist controller index show

- app/controllers/histories_controller.rb
- 購入処理後にフラッシュメッセージが表示されるようになりました
> [Fixed]Add flash message after create a history

- app/assets/stylesheets/items.scss
- app/assets/stylesheets/users.scss
- app/views/artists/index.html.erb
- app/views/items/edit.html.erb
- app/views/items/new.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/show.html.erb
CSSを編集しました。
・横幅を％で指定していたところをpxに変更
・それに伴い、同じクラスの部分を修正しました。
> [update]CSS artists/index items/edit items/new users/show

- app/assets/stylesheets/following_artists.scss
- app/views/following_artists/index.html.erb
- app/views/following_artists/show.html.erb
controller
show
index
を修正しております
> [modified] following_artist scss

- app/assets/stylesheets/application.scss
- app/views/users/about.html.erb
> [modified]About

- app/assets/stylesheets/following_artists.scss
- app/assets/stylesheets/items.scss
- app/views/following_artists/index.html.erb
- app/views/following_artists/show.html.erb
modified:   app/assets/stylesheets/following_artists.scss
modified:   app/assets/stylesheets/items.scss
modified:   app/views/following_artists/index.html.erb
modified:   app/views/following_artists/show.html.erb
> [modified] following_artist index show scss

- app/assets/stylesheets/following_artists.scss
- app/views/following_artists/show.html.erb
- フォローアーティストのshowで、選択中のアーティストに枠が表示されるようになりました。
>  [modified]followingArtists#show & controllers

- app/assets/stylesheets/following_artists.scss
- app/views/following_artists/show.html.erb
> [update]CSS following_artist

- app/assets/stylesheets/following_artists.scss
> [update]CSS following

- app/assets/stylesheets/following_artists.scss
- app/views/following_artists/show.html.erb
> [modified]following artists(view & CSS)

- app/assets/stylesheets/following_artists.scss
- app/views/following_artists/show.html.erb
- フォローアーティスト詳細ページの変更(NEWの表示・イベント日付表示・イベント名の表示制限)
> [modified]Following Artists index & CSS

- app/views/layouts/application.html.erb
- app/views/users/registrations/new.html.erb
> [Fixed]User#new

- app/assets/stylesheets/carts.scss
- app/views/carts/index.html.erb
> [update]CSS cart/index

- app/assets/stylesheets/carts.scss
- app/views/carts/confirm.html.erb
- app/views/carts/index.html.erb
> [update]CSS cart

- app/views/carts/index.html.erb
link_to cart.item.title, item_path(cart.item.id)
> [modified] carts_index

- app/assets/stylesheets/history.scss
- app/views/histories/show.html.erb
- app/views/items/edit.html.erb
・受注一覧のステータスをenumと揃えました。
・商品詳細編集画面に商品の削除ボタンを追加しました。
> [update]histories/show items/edit

- app/assets/stylesheets/users.scss
- app/views/users/index.html.erb
> [update]users/index

- app/controllers/application_controller.rb
- アプリケーションコントローラーの変更(ログイン後のページ遷移)
> [modified]application controller
